### ISSUE TITLE
OAuth convenience function get_oauth_access_token improvements

### ISSUE THREAD

**Issue by billdeitrick** [billdeitrick/pypco#17]
This function should:
* Return a Dict instead of the Response object it currently does.
* Handle a transport-level timeout gracefully

**Comment by billdeitrick** [comment]
This is documented, but doesn't exist yet. 😏

**Comment by pastorhudson** [comment]
This would be really nice

**Comment by billdeitrick** [comment]
This is done in f9da44073f6f207377f3224ac57aea7ab5327f6d.
