### ISSUE TITLE
OAuth convenience function refresh_access_token

### ISSUE THREAD

**Issue by billdeitrick** [billdeitrick/pypco#18]
We should create an OAuth convenience function to help with refreshing access tokens. We provide these for creating access_tokens the first time, but not for refreshing.

**Comment by billdeitrick** [comment]
This is documented, but doesn't exist yet. :smirk:

**Comment by pastorhudson** [comment]
What do you have in mind? Just the function to:

```
def get_refresh_token(token):
    refresh_token = magic_foo()
    return refresh_token
```

Or are you thinking about storing tokens and keeping them refreshed for multi tenet applications?

**Comment by billdeitrick** [comment]
The former. I think storing tokens/handling refreshes in a multi-tenant scenario should be the responsibility of whatever app is using pypco, not pypco itself.

**Comment by billdeitrick** [comment]
Done in 0112c505e7c022330be31032daf0b6f473592373 for 1.0.
