### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by openaiken** [billdeitrick/pypco#24]
Hey, I just wanted to say thank you for working on this! Open Source can be thankless in general but especially for people who work on stuff like this. Looking forward to playing with it one day and maybe using it to help bring open source presentation software to churches. God bless.

**Comment by billdeitrick** [comment]
Thanks for your kind words @openaiken--I hope it will be useful for you! A 1.0 release is in the works, so stay tuned. 🙂

**Comment by pastorhudson** [comment]
@openaiken If you're thinking about adding planning center support to openLP I think that would be awesome!

And yes @billdeitrick is the man!

**Comment by openaiken** [comment]
That is the dream. I'm good at object oriented programming but I have a lot to learn before I can touch this. It's on the todo list though...

**Comment by pastorhudson** [comment]
I've done a good bit of work with the pco api, and this library specifically so if you get stuck trying to wrangle the api hit me up. There's also another guy who took "son of projector" which is planning centers opensourced worship media app and reworked it. He would know a lot about the bits you need to get access to he is Butch Davis and he hangs out on the Planning Center Online Slack #api channel
