### ISSUE TITLE
Group Objects not accessible

### ISSUE THREAD

**Issue by mphuff** [billdeitrick/pypco#29]
It appears that the Group objects and related items (attendance, membership, etc) are not available at all.

It is marked as a BETA API in Planning Center's APIs but could potentially be brought in here. 

https://developer.planning.center/docs/#/apps/groups/2018-08-01

**Comment by pastorhudson** [comment]
The upcoming 1.0 that @billdeitrick is working on will allow you to give it any endpoint by url rather than the current model schema. That should let us grab any endpoint even if it's not published/official.

**Comment by mphuff** [comment]
That's good to know @pastorhudson

**Comment by pastorhudson** [comment]
Awesome I'm closing this one up. Feel free to reopen if you need to.
