### ISSUE TITLE
Minor Copy Errors in pypco/models/services.py

### ISSUE THREAD

**Issue by Chalta** [billdeitrick/pypco#7]
Rehearsal misspelled in ENDPOINT_NAME:

```class SplitTeamRehearsalAssignment(ServicesModel): ENDPOINT_NAME = 'split_team_rehersal_assignments'  # noqa: E701,E302,E501```

Copy/paste error in name in initial comment.

```Models for PCO people.```

**Comment by billdeitrick** [comment]
[Fixed](https://github.com/billdeitrick/pypco/commit/eb6e44f57021c5f198a300b7d0d94ec31d54a548). Thanks for reporting this!

**Comment by pastorhudson** [comment]
Thanks @Chalta!
