### ISSUE TITLE
How to query by

### ISSUE THREAD

**Issue by impactcolor** [billdeitrick/pypco#75]
Thanks for this awesome package.  Just wondering how can I query by?
The api documentation says Query by is optional.
in example: 
`for person in pco.iterate('/people/v2/people'):`
I attempted 
'/people/v2/people?gender=male' to no avail.  I wanted here to return all the people where male.

**Comment by impactcolor** [comment]
Never mind found in the documentation here:
https://github.com/billdeitrick/pypco/blob/master/docs/source/apitour.md

**Comment by pastorhudson** [comment]
Adding this for future searches.

You can find the query parameters here: https://developer.planning.center/docs/#/apps/people/2023-03-21/vertices/person.
Scroll down to Query By. You'll see all the options. Also the API Explorer https://api.planningcenteronline.com/explorer provides a lot of help in constructing the url.
